# Generated by Django 3.1.1 on 2020-10-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades de cada empleado',
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['-first_name', 'last_name'], 'verbose_name': 'Pesonal General', 'verbose_name_plural': 'Personal de la empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('first_name', 'last_name')},
        ),
    ]
