# Generated by Django 3.1.1 on 2020-10-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_empleado_hoja_vida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='hoja_vida',
            new_name='hoja_de_vida',
        ),
    ]
