# Generated by Django 3.1.1 on 2020-11-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_empleado_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
    ]
